name: Test

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  test-general:
    uses: _tests-general.yml
  test-pc:
    uses: _tests-platform.yml
    with:
      NAMES_PATH: PC/names
  test-console:
    uses: _tests-platform.yml
    with:
      NAMES_PATH: Console/names
